# -*- coding: utf-8 -*-
"""langgraph_tools_Bindings_agents_groq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iDZpU8h0YcJp3shVc7Bpzkx7acfLtuza
"""

!pip install -U langchain langchain-community langgraph langchain-groq duckduckgo-search

from IPython.display import Image, display
from langgraph.graph import StateGraph, START
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage
from langgraph.prebuilt import ToolNode, tools_condition
from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph.message import add_messages

class State(TypedDict):
    messages: Annotated[list, add_messages]

!pip install -U ddgs

from langchain_community.tools import DuckDuckGoSearchRun
search = DuckDuckGoSearchRun()
search.invoke("Obama's first name?")

search.invoke("What is AI?")

search.invoke("What happened in the AI industry this week?")

search.invoke("Who is Elon Mus")

from langchain_community.tools import DuckDuckGoSearchRun

def search_duckduckgo(query: str):
    """Searches DuckDuckGo using LangChain's DuckDuckGoSearchRun tool."""
    search = DuckDuckGoSearchRun()
    return search.invoke(query)

# Example usage
result = search_duckduckgo("what are AI agent")
print(result)

def multiply(a:int,b:int) -> int:
    """
    Multiply a and b
    """
    return a* b

def add(a:int,b:int) -> int:
    """
    Adds a and b
    """
    return a + b

import os
from getpass import getpass

if not os.getenv("GROQ_API_KEY"):
    os.environ["GROQ_API_KEY"] = getpass("prajwal_api_key")

llm = ChatGroq(
    model="openai/gpt-oss-120b",
    temperature=0,
    api_key=os.environ["GROQ_API_KEY"]
)

llm.invoke('hello').content

tools = [search_duckduckgo, add, multiply]
llm_with_tools = llm.bind_tools(tools)

def chatbot(state: State):
    return {"messages": [llm_with_tools.invoke(state["messages"])]}

from langgraph.prebuilt import ToolNode, tools_condition

graph_builder = StateGraph(State)

# Define nodes
graph_builder.add_node("assistant",chatbot)
graph_builder.add_node("tools",ToolNode(tools))

#define edges
graph_builder.add_edge(START,"assistant")
graph_builder.add_conditional_edges("assistant",tools_condition)
graph_builder.add_edge("tools","assistant")

react_graph=graph_builder.compile()

# To see the graph’s connection visually

display(Image(react_graph.get_graph().draw_mermaid_png()))

response = react_graph.invoke({"messages": [HumanMessage(content="what is the weather in delhi. Multiply it by 2 and add 5.")]})
print(response["messages"])

response = react_graph.invoke({"messages":[HumanMessage(content="Who is the current CEO of NVIDIA?")]})
print(response["messages"])

response = react_graph.invoke({
    "messages": [
        HumanMessage(content="Who is the current CEO of NVIDIA?")
    ]
})

print(response["messages"])

response = react_graph.invoke({
    "messages": [
        HumanMessage(content="Who is the current CEO of NVIDIA?")
    ]
})

print(response["messages"][-1].content)